# Generated by Django 2.2.5 on 2019-09-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_moteur_voiture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100),
            preserve_default=False,
        ),
    ]
