# Generated by Django 2.2.5 on 2019-09-26 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_field', models.URLField(unique=True, verbose_name='URL')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('pseudo', models.CharField(blank=True, max_length=50, null=True)),
                ('nb_acces', models.IntegerField(default=0, verbose_name="Nombre d'accès")),
            ],
        ),
    ]
